import "./globals.css";

export const metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>This is the header</header>
        {children}
        <footer>footer</footer>
      </body>
    </html>
  );
}
