import Footer from "@/components/Footer";
import "./globals.css";
import Header from "@/components/Header";
// google font
import { Montserrat } from "next/font/google";

export const metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

// font
const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <body className="flex-grow">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
